DROP DATABASE IF EXISTS example;
CREATE DATABASE example;
USE example;

CREATE TABLE users (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(100)
);

DROP DATABASE IF EXISTS sample;
CREATE DATABASE sample;